spring:
  application:
    name: "discovery"
#  config:
#    import: "configserver:http://localhost:8071/"
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
