#spring:
#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      group-id: wallet-group-3
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: '*'
#              spring.json.type.mapping: com.wallet.notificationservice.dto.Customer:com.wallet.consumer.dto.Customer

server:
  port: 9292

